\documentclass{article}

\usepackage{arxiv}

\usepackage[utf8]{inputenc} % allow utf-8 input
\usepackage[T1]{fontenc}    % use 8-bit T1 fonts
\usepackage{lmodern}        % https://github.com/rstudio/rticles/issues/343
\usepackage{hyperref}       % hyperlinks
\usepackage{url}            % simple URL typesetting
\usepackage{booktabs}       % professional-quality tables
\usepackage{amsfonts}       % blackboard math symbols
\usepackage{nicefrac}       % compact symbols for 1/2, etc.
\usepackage{microtype}      % microtypography
\usepackage{graphicx}

\title{Prediction of Adverse Drug Reactions - Using Advanced Statistical
Methods}

\author{
    Arshad Ahamed Shajahan
   \\
    School of Mathematics \\
    University of Galway \\
  Galway, Ireland \\
  \texttt{\href{mailto:A.Shajahan2@universityofgalway.ie}{\nolinkurl{A.Shajahan2@universityofgalway.ie}}} \\
   \And
    Sai Shasank Dandu
   \\
    School of Mathematics \\
    University of Galway \\
  Galway, Ireland \\
  \texttt{\href{mailto:S.Dandu2@universityofgalway.ie}{\nolinkurl{S.Dandu2@universityofgalway.ie}}} \\
  }


% tightlist command for lists without linebreak
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}

% From pandoc table feature
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}

% Pandoc citation processing
%From Pandoc 3.1.8
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{#1\hfill\break}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{#1}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{#1}\break}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

\usepackage{amsmath}
\usepackage{float}
\begin{document}
\maketitle


\begin{abstract}
Adverse Drug Reactions represent a major challenge in pharmacovigilance
and drug safety, contributing significantly to patient morbidity,
mortality, and healthcare costs. Due to the high cost and time required
to run clinical trials, there is significant interest in accurate
computational methods that can aid in the prediction of ADRs for new
drugs. So in this paper, a wider range of statistical models were
developed and evaluated in predicting ADRs using two complementary
sources of drug information, drug gene interaction profiles and chemical
fingerprints. The models evaluated include a Naïve Baseline, Kernel
Regression, Support Vector Machines with linear and RBF kernels, and a
novel Weighted Non-negative Matrix Factorisation framework combined with
Kernel Regression. Performance is assessed across 5-fold
cross-validation using the Area Under the ROC Curve and Area Under the
Precision-Recall Curve. Our results demonstrate that the Weighted NMF
with Kernel Regression achieves the highest AUPR (0.5007 ± 0.0021),
making it the most effective method for handling the imbalanced nature
of ADR datasets, while VKR NMF achieves the highest AUROC (0.9183 ±
0.0025). An interactive web application was further developed enabling
real time single drug ADR prediction.
\end{abstract}


\section{Introduction}\label{introduction}

Adverse Drug Reactions (ADRs) are unintended, harmful responses to
medications administered at normal therapeutic doses. ADRs are among the
leading causes of hospitalisation and morbidity worldwide, with a pooled
median prevalence of ADR-related hospital admissions estimated at 6.3\%
in developed countries and 5.5\% in developing countries, based on a
systematic review of studies published between 2000 and 2015 (Angamo et
al. 2016).

Beyond the human cost, ADRs impose substantial financial burdens on
healthcare systems. The same European Commission analysis estimated that
197,000 deaths per year in the EU are attributable to ADRs, with a total
societal cost of €79 billion as of 2008 ({Formosa et al.} 2018).
Traditional approaches to ADR detection rely primarily on post market
pharmacovigilance, monitoring drug safety signals after a drug has
already entered clinical use (Koyama et al. 2024). While these methods
are effective, someone must experience an adverse reaction in real life
to flag such behaviour. Hence, computational prediction of ADRs, offers
the potential to anticipate safety issues before clinical exposure,
informing drug development decisions and personalising treatment.

Drugs can be characterised by their interaction profiles with genes and
by their chemical structure, both of which are expected to carry
information about their biological activity and, by extension, their
side effect profiles. Therefore, the drug gene profiles and chemical
structure were used as primary inputs for the model in predicting ADR's.
However, the construction of such models faces two fundamental
statistical challenges:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Sparsity}: The drug side effect matrix is extremely sparse.
  Most drug side effect pairs are unobserved, not because the side
  effect is absent, but because it has not been reported or studied.
\item
  \textbf{Class Imbalance}: The number of known positive drug side
  effect associations is vastly smaller than the number of negatives,
  making standard classifiers biased toward predicting the majority
  (negative) class.
\end{enumerate}

Addressing these challenges requires careful model selection and
evaluation. The Area Under the Receiver Operating Characteristic curve
(AUROC) is a widely used metric that quantifies a classifier's ability
to discriminate between positive and negative classes across all
classification thresholds, calculated as the area under the curve
plotting the true positive rate (sensitivity) against the false positive
rate (1 - specificity). However, the ADR dataset possess a highly
imbalanced classes where positive cases are rare relative to the
negative cases.

The Area Under the Precision Recall Curve (AUPR) plots, precision (the
proportion of predicted positives that are true positives) against
recall (the proportion of actual positives correctly identified) across
all thresholds. Since precision is sensitive to number of false
positives, AUPR provides a more informative and discriminative
assessment of the model performance. So, both AUPR and AUROC has been
evaluated for all the models.

The previous research work from (Zhong et al. 2024) serves as a base for
our research. It addressed the core issue with imbalanced datasets but
introducing a novel method of using Non-Negative Matrix Factorization.
In this research, the results from the previous paper is replicated and
further extended the work by expanding the dataset and by introducing a
novel method, Weighted Non-Negative Matrix Factorization for predicting
ADRs using drug gene interaction (DGI) profiles and chemical
fingerprints.

In the remainder of this paper, Section 2 describes the datasets,
Section 3 \ldots{} and so on.

\section{Data}\label{data}

The primary data for this study was accessed through various publicly
available sources. In particular, the SIDER 4.1 database was used to
obtain drug side-effect information. SIDER (``Side Effect Resource'') is
a publicly available database that compiles information on marketed
drugs and their recorded adverse drug reactions, extracted from package
inserts and clinical trial data. the current release contains data on
1,430 drugs, 5,880 ADRs, and 140,064 drug--ADR pairs (Kuhn et al. 2016).

Additionally, the Drug--Gene Interaction Database (DGIdb 4.0) was used
to obtain drug--gene interaction data. DGIdb is a web resource that
aggregates information on drug--gene interactions and druggable genes
from publications, databases, and other web-based sources, with drug,
gene, and interaction data normalised and merged into conceptual groups
({Freshour et al.} 2021).

PubChem, a freely accessible chemical database maintained by the
National Center for Biotechnology Information (NCBI), was used to
retrieve drug chemical structure fingerprints. Mapping the drug names to
side effects, gene interactions, and chemical fingerprints resulted in
973 unique data points across the three databases. Table 1 provides an
overview of the dimensionality of the three databases.

All three datasets were binarised (binary matrices) prior to modelling.
The DGI and Chemical fingerprints data had all the drugs in the first
column. Genes and generated fingerprints were presented in each columns
in the respective datasets. Table 1 summarises the dataset dimensions.

\begin{longtable}[]{@{}ll@{}}
\caption{Summary of dataset dimensions.}\tabularnewline
\toprule\noalign{}
Feature Type & Dimensionality \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Feature Type & Dimensionality \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Drug-Gene Interaction & 973 × 3,647 \\
Chemical Fingerprints & 973 × 1,024 \\
Side Effect Matrix & 973 × 5779 \\
\end{longtable}

\subsection{Class Imbalance in the
dataset}\label{class-imbalance-in-the-dataset}

The drug side effect matrix is highly sparse, with a positive rate well
below 10\% for most side effects. This severe class imbalance motivates
the use of AUPR as a primary evaluation metric alongside AUROC, since
AUROC can appear inflated in imbalanced settings. In the entire dataset,
about 97\% of the data represents the negative class and remaining as
positive class

\section{Methods}\label{methods}

Initially exploratory data analysis, including descriptive statistics
and heatmaps, was performed to ??????. Furthermore, to predict the ADR,
six modelling approaches of increasing sophistication were employed. All
models take as input either the DGI matrix, the chemical fingerprints
matrix, or both, and output a probability score for each drug side
effect pair. 5-fold cross validation was performed to assess the
predictive ability of the proposed models. Due to high sparsity of the
drug side effect matrix (with a positive rate well below 10\% for most
side effects), AUPR was used as a primary evaluation metric alongside
AUROC, since AUROC can appear inflated in imbalanced settings. Below we
briefly discuss the proposed modelling approaches.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Naïve Baseline} The Naïve Baseline assigns to each drug-side
  effect pair the marginal prevalence of that side effect across the
  training set. This model ignores the drug gene interaction and
  chemical fingerprints data, and predicts probability based on the
  prevalence of side effects among the given dataset.
\item
  \textbf{Kernel Regression} Kernel Regression (KR) operates by mapping
  drugs into a high dimensional similarity space. For a new drug (d),
  its side effect probabilities are predicted as a weighted average of
  training drugs' side effect profiles, where weights are proportional
  to their similarity to new drug (d). This model projects the new drug
  into the same high-dimensional space as the training drugs and
  predicts its side effects based on its position in that space.
\item
  \textbf{Support Vector Machine (SVM)} The SVM models treat ADR
  prediction as a binary classification problem, training a separate
  classifier per side effect. We evaluated two kernel configurations:
  SVM-Linear: A linear SVM in the feature space, appropriate when the
  number of features exceeds the number of samples. SVM-RBF: An SVM with
  a Radial Basis Function (RBF) kernel, which maps the data into an
  infinite-dimensional feature space and finds a maximum-margin
  hyperplane there.
\item
  \textbf{Non-negative Matrix Factorisation with Kernel Regression (VKR
  NMF)} Non-negative Matrix Factorisation (NMF) decomposes the training
  side effect matrix into two lower-rank non-negative matrices:
  \[Y \approx UH^\top, \quad U \in \mathbb{R}^{n \times k}_+, \quad H \in \mathbb{R}^{s \times k}_+\]
  where min(n,s) is the number of latent features. The matrix `U'
  captures the drug level latent representation (side effect profiles in
  latent space), and `H' captures the side effect level loadings. For
  prediction, Kernel Regression is applied to project new drugs into the
  latent space:
\end{enumerate}

\[\hat{U}_{d^*} = K(d^*, D_{\text{train}}) W\]

where `W' is a weight matrix learned by regressing `U' onto the kernel
matrix. The predicted side effects are then reconstructed as:

\[\hat{Y}_{d^*} = \hat{U}_{d^*} H^\top\]

This approach captures latent structure in the side effect matrix while
leveraging drug similarity for prediction.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  \textbf{Weighted NMF with Kernel Regression (VKR Weighted NMF)}
  Standard NMF treats all entries of `Y' equally, which is problematic
  given sparsity and class imbalance. Weighted NMF addresses this by
  upweighting observed positive entries in the factorisation objective:
\end{enumerate}

\[\min_{U \geq 0, H \geq 0} \sum_{i,j} W_{ij} \left(Y_{ij} - [UH^\top]_{ij}\right)^2\]
where \(W_{ij} > 1\) for observed positive pairs and \(W_{ij} = 1\)
otherwise. This encourages the model to accurately reconstruct the rare
positive associations that are most predictively valuable. Kernel
Regression is then applied as in the standard NMF case to project new
drugs. This model is designed specifically to address the imbalance
problem, prioritising precision on positive predictions. The penalty
factor of 1:10 is applied, for predicting all true outcomes wrongly.
Since the dataset is imbalanced, this penalty adds weightage to predict
all the true positives correctly.

\section{Results}\label{results}

Performing Exploratory Data Analysis (EDA) in the dataset, brought out
some key findings and understaandings about the ADR dataset. In Figure
\ref{fig:fig-most-common-drug} you can see the drugs associated with the
largest number of reported side effects. The results show that a
relatively small number of ADRs account for a substantial proportion of
all reported events, indicating a highly skewed distribution of side
effects. The drugs mentioned below interacts with our central nervous
system (CNS) and hence the large number of side effects associated with
them.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth]{figures/common_se} 

}

\caption{Drugs with most number of side effects and most frequent side effects\label{fig:fig-most-common-drug}}\label{fig:fig-most-common-drug}
\end{figure}

The below Figure \ref{fig:fig-se-distribution} describes the number of
drugs associated with number of side effects. Several drugs are
associated with more than 200 side effects and handful of them were
associated with as high as 800 side effects.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth]{figures/distribution_of_se} 

}

\caption{Distribution of side effects}\label{fig:fig-se-distribution}
\end{figure}

Since most of model functions based on similarity between the drug
profiles, the Figure 3 heatmap illustrates the drug similarity based on
side effects. Distinct clustering patterns can be observed, suggesting
that groups of drugs share similar adverse reaction profiles. The
heatmaps also demonstrate the sparsity of the interaction matrix, with
positive drug-side effect associations representing only a small
fraction of all possible combinations. Overall, the visualisation
highlights the heterogeneous nature of ADR profiles and the highly
imbalanced characteristics of the prediction task.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth]{figures/drug_similarity} 

}

\caption{Drug Similarity Heatmap}\label{fig:fig-se-heatmap}
\end{figure}

\subsection{Overall Model Performance}\label{overall-model-performance}

Table 1 summarises the predictive performance of all evaluated methods
using five-fold cross-validation, where the dataset was randomly
partitioned into 75\% training data and 25\% testing data in each fold.
Performance is reported as the mean ± standard deviation of the Area
Under the Receiver Operating Characteristic Curve (AUROC) and the Area
Under the Precision--Recall Curve (AUPR) across the five folds, with the
highest average value for each metric highlighted.

\begin{verbatim}
## Warning: package 'knitr' was built under R version 4.5.2
\end{verbatim}

\begin{longtable}[]{@{}lll@{}}
\caption{Mean performance across five-fold cross-validation (AUROC and
AUPR)}\tabularnewline
\toprule\noalign{}
Method & Mean\_AUROC\_SD & Mean\_AUPR\_SD \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Method & Mean\_AUROC\_SD & Mean\_AUPR\_SD \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Naïve Baseline & 0.9101 ± 0.0024 & 0.3584 ± 0.0075 \\
Kernel Regression & 0.8745 ± 0.0051 & 0.4155 ± 0.0051 \\
SVM Linear & 0.7955 ± 0.0097 & 0.3122 ± 0.0124 \\
SVM RBF & 0.9001 ± 0.0041 & 0.3919 ± 0.0068 \\
VKR NMF & 0.9183 ± 0.0027 & 0.4230 ± 0.0033 \\
VKR Weighted NMF & 0.8551 ± 0.0035 & 0.5001 ± 0.0022 \\
VKR SVD & 0.9098 ± 0.0033 & 0.4341 ± 0.0049 \\
\end{longtable}

Table 2. Summary of predictive performance for all evaluated methods
using five-fold cross-validation with a 75\% training and 25\% testing
split, reporting the mean AUROC and AUPR (± standard deviation) across
the five folds. The evaluated methods achieved mean AUROC values ranging
from 0.7955 ± 0.0097 to 0.9183 ± 0.0027, while mean AUPR values ranged
from 0.3122 ± 0.0124 to 0.5001 ± 0.0022.

Among all evaluated approaches, VKR NMF achieved the highest mean AUROC
(0.9183 ± 0.0027) together with a mean AUPR of 0.4230 ± 0.0033,
indicating the strongest overall discrimination between positive and
negative ADR associations.

VKR Weighted NMF produced the highest mean AUPR (0.5001 ± 0.0022), while
achieving a mean AUROC of 0.8551 ± 0.0035. VKR SVD also demonstrated
strong and consistent performance across all five folds, obtaining a
mean AUROC of 0.9098 ± 0.0033 and a mean AUPR of 0.4341 ± 0.0049.

The Naïve Baseline achieved the second-highest mean AUROC (0.9101 ±
0.0024), although its mean AUPR (0.3584 ± 0.0075) was considerably lower
than those of the VKR-based methods. Kernel Regression and SVM RBF
demonstrated intermediate performance across both evaluation metrics,
whereas SVM Linear produced the lowest overall predictive performance,
with a mean AUROC of 0.7955 ± 0.0097 and a mean AUPR of 0.3122 ± 0.0124.

\subsection{ROC and Threshold-Based Performance
Analysis}\label{roc-and-threshold-based-performance-analysis}

Figure 4 presents the Receiver Operating Characteristic (ROC) curves for
all evaluated methods. VKR NMF achieved the strongest overall
discrimination between positive and negative ADR associations, producing
the highest AUROC among all evaluated approaches. VKR SVD and the Naïve
Baseline also demonstrated competitive ROC performance, whereas SVM
Linear exhibited the weakest discrimination. Kernel Regression and SVM
RBF showed intermediate performance. Receiver Operating Characteristic
(ROC) curves for all evaluated methods. (b) Precision, recall, and F1
score as a function of the decision threshold for the VKR NMF model. The
dashed vertical line indicates the optimal threshold (0.2265),
corresponding to precision = 0.4355, recall = 0.4760, and F1 = 0.4549.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth]{figures/2a} 

}

\caption{Precision Recall Curve}\label{fig:fig-precision-recall}
\end{figure}

Figure 5 presents the variation of precision, recall, and F1 score for
the VKR NMF model across different decision thresholds. As the decision
threshold increases, recall decreases while precision generally
increases, illustrating the trade-off between identifying true ADR
associations and reducing false positive predictions. The F1 score,
which balances precision and recall, reaches its maximum value of 0.4549
at a threshold of 0.2265, corresponding to a precision of 0.4355 and a
recall of 0.4760. The optimal threshold is considerably lower than the
conventional value of 0.5, indicating that a lower decision boundary
provides a more balanced prediction performance for this highly
imbalanced ADR dataset.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth]{figures/2b} 

}

\caption{ROC Curve for all methods}\label{fig:fig-roc}
\end{figure}

\subsection{Sensitivity and Specificity Across Decision
Thresholds}\label{sensitivity-and-specificity-across-decision-thresholds}

Figure 6 presents the sensitivity and specificity of each evaluated
method across decision thresholds ranging from 0.1 to 0.9. The heatmaps
illustrate each model's ability to correctly identify true ADR
associations (sensitivity) while correctly rejecting negative
associations (specificity). Most models follow the expected pattern in
which sensitivity decreases as the decision threshold increases, while
specificity increases. The Naïve Baseline, Kernel Regression, SVM
variants, VKR NMF, and VKR SVD all exhibit high sensitivity at lower
thresholds, followed by a gradual decline as more stringent decision
boundaries are applied. By a threshold of 0.5, sensitivity for these
models has decreased substantially, whereas specificity exceeds 0.99,
indicating a strong ability to avoid false positive predictions. In
contrast, VKR Weighted NMF displays a markedly different behaviour.
Across the entire threshold range, it maintains substantially higher
sensitivity than the remaining methods, achieving 0.976 at a threshold
of 0.1 and remaining at 0.918 even at a threshold of 0.9. This high
sensitivity is accompanied by comparatively lower specificity, which
increases from 0.287 at threshold 0.1 to 0.763 at threshold 0.9. The
heatmaps therefore demonstrate the distinct operating characteristics of
VKR Weighted NMF relative to the other evaluated approaches.

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth]{figures/heatmap} 

}

\caption{Sensitivity and specificity heatmaps across all methods and decision thresholds (0.1–0.9). Green indicates higher values, whereas red indicates lower values.}\label{fig:fig-heatmap}
\end{figure}

Sensitivity and specificity heatmaps across all methods and decision
thresholds (0.1--0.9). Green indicates higher values, whereas red
indicates lower values.

\subsection{Five-Fold Cross-Validation Performance
Comparison}\label{five-fold-cross-validation-performance-comparison}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 24\tabcolsep) * \real{0.1333}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 24\tabcolsep) * \real{0.0667}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 24\tabcolsep) * \real{0.0667}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 24\tabcolsep) * \real{0.0667}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 24\tabcolsep) * \real{0.0667}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 24\tabcolsep) * \real{0.0667}}
  >{\raggedright\arraybackslash}p{(\linewidth - 24\tabcolsep) * \real{0.1185}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 24\tabcolsep) * \real{0.0593}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 24\tabcolsep) * \real{0.0593}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 24\tabcolsep) * \real{0.0593}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 24\tabcolsep) * \real{0.0593}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 24\tabcolsep) * \real{0.0593}}
  >{\raggedright\arraybackslash}p{(\linewidth - 24\tabcolsep) * \real{0.1185}}@{}}
\caption{Five-fold cross-validation results for all methods (AUROC and
AUPR)}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Method
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
AUROC\_F1
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
AUROC\_F2
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
AUROC\_F3
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
AUROC\_F4
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
AUROC\_F5
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
AUROC\_Mean\_SD
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
AUPR\_F1
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
AUPR\_F2
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
AUPR\_F3
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
AUPR\_F4
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
AUPR\_F5
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
AUPR\_Mean\_SD
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Method
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
AUROC\_F1
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
AUROC\_F2
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
AUROC\_F3
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
AUROC\_F4
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
AUROC\_F5
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
AUROC\_Mean\_SD
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
AUPR\_F1
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
AUPR\_F2
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
AUPR\_F3
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
AUPR\_F4
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
AUPR\_F5
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
AUPR\_Mean\_SD
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Naive Baseline & 0.9089 & 0.9078 & 0.9083 & 0.9116 & 0.9142 & 0.9101 ±
0.0024 & 0.3615 & 0.3674 & 0.3485 & 0.3641 & 0.3506 & 0.3584 ± 0.0075 \\
Kernel Regression & 0.8676 & 0.8727 & 0.8718 & 0.8787 & 0.8819 & 0.8745
± 0.0051 & 0.4151 & 0.4228 & 0.4090 & 0.4110 & 0.4194 & 0.4155 ±
0.0051 \\
SVM Linear & 0.7828 & 0.8003 & 0.8000 & 0.7857 & 0.8087 & 0.7955 ±
0.0097 & 0.3156 & 0.3243 & 0.3225 & 0.2902 & 0.3085 & 0.3122 ± 0.0124 \\
SVM RBF & 0.8969 & 0.8974 & 0.9018 & 0.8970 & 0.9074 & 0.9001 ± 0.0041 &
0.3945 & 0.4030 & 0.3860 & 0.3923 & 0.3836 & 0.3919 ± 0.0068 \\
VKR NMF & 0.9158 & 0.9163 & 0.9165 & 0.9204 & 0.9226 & 0.9183 ± 0.0027 &
0.4241 & 0.4282 & 0.4182 & 0.4212 & 0.4233 & 0.4230 ± 0.0033 \\
VKR Weighted NMF & 0.8510 & 0.8533 & 0.8600 & 0.8587 & 0.8527 & 0.8551 ±
0.0035 & 0.5004 & 0.5006 & 0.4960 & 0.5025 & 0.5010 & 0.5001 ± 0.0022 \\
VKR SVD & 0.9051 & 0.9072 & 0.9106 & 0.9118 & 0.9143 & 0.9098 ± 0.0033 &
0.4338 & 0.4427 & 0.4292 & 0.4296 & 0.4353 & 0.4341 ± 0.0049 \\
\end{longtable}

Table 3. presents the complete five-fold cross-validation results for
all evaluated methods, reporting AUROC and AUPR scores for each fold
along with their mean and standard deviation. VKR NMF achieved a mean
AUROC of 0.9183 ± 0.0027 and a mean AUPR of 0.4230 ± 0.0033 across the
five folds. VKR Weighted NMF obtained a mean AUROC of 0.8551 ± 0.0035
and a mean AUPR of 0.5001 ± 0.0022. VKR SVD recorded a mean AUROC of
0.9098 ± 0.0033 and a mean AUPR of 0.4341 ± 0.0049. The Naïve Baseline
achieved a mean AUROC of 0.9101 ± 0.0024 and a mean AUPR of 0.3584 ±
0.0075. Kernel Regression obtained a mean AUROC of 0.8745 ± 0.0051 and a
mean AUPR of 0.4155 ± 0.0051. SVM Linear recorded a mean AUROC of 0.7955
± 0.0097 and a mean AUPR of 0.3122 ± 0.0124, while SVM RBF achieved a
mean AUROC of 0.9001 ± 0.0041 and a mean AUPR of 0.3919 ± 0.0068.

\subsection{An Interactive Application for ADR
Prediction}\label{an-interactive-application-for-adr-prediction}

\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth]{figures/app1} 

}

\caption{Interactive Application For ADR Prediction}\label{fig:fig-app-1}
\end{figure}
\begin{figure}[H]

{\centering \includegraphics[width=0.7\linewidth]{figures/app2} 

}

\caption{Interactive Application For ADR Prediction}\label{fig:fig-app-2}
\end{figure}

Figure 7 and 8, displays a snapshot of an interactive web application
allowing users to input a drug and receive a ranked list of predicted
adverse drug reactions from the best-performing model. The app can be
run locally where the code, datasets, and deployment steps are all
available in the paper's GitHub repository.

\section{Discussion}\label{discussion}

Adverse drug reactions cause significant patient harm and are a major
driver of drug withdrawals from the market, and therefore remain a
critical concern in pharmacovigilance and drug development
((\textbf{Lazarou?} et al.~1998)). Being able to predict them
computationally before a drug reaches widespread clinical use is
therefore a problem that genuinely matters. This study set out to
evaluate whether a range of statistical and machine learning methods,
drawing on drug-gene interaction profiles, chemical fingerprints, and
side-effect similarity, could predict adverse drug reaction associations
in a robust and interpretable way. The results demonstrate that this is
feasible, while also revealing important and often underappreciated
challenges in how ADR prediction models should be evaluated.

A key point from this work is that the choice of evaluation metric is
very important for highly imbalanced biomedical datasets. In this study,
AUPR is used as the main metric, while AUROC is treated as a secondary
measure. This is because the dataset is heavily imbalanced, with far
more negative drug--reaction pairs than positive ones. The Naïve
Baseline highlights this issue clearly. Even without using any
meaningful drug-specific information, it still achieves an AUROC of over
0.91, which can make it look like a strong model. However, its AUPR is
only 0.36, showing that it performs poorly in correctly identifying the
rare positive cases. This difference shows that AUROC can sometimes give
an overly optimistic view of performance in imbalanced datasets, while
AUPR gives a more realistic picture of how well the model actually works
in practice. This finding is also in line with previous studies, which
suggest that precision--recall based evaluation is more reliable than
ROC analysis when the data is highly imbalanced ((\textbf{Saito?} and
Rehmsmeier 2015)).

The difference between VKR NMF and VKR Weighted NMF shows an important
trade-off in ADR prediction. VKR NMF performs best in terms of
cross-validated AUROC and gives more precise predictions at standard
thresholds. This makes it useful when we need high confidence in the
predicted drug--ADR associations. On the other hand, VKR Weighted NMF
focuses more on sensitivity across all thresholds. It is able to detect
most true ADR associations, even at higher thresholds, but this reduces
its specificity, meaning it produces more false positives. In practical
use, both models serve different purposes. VKR Weighted NMF is better
for early-stage drug safety screening, where it is important not to miss
potential risks. VKR NMF is more suitable for later-stage or
confirmatory analysis, where higher precision is more important
((\textbf{Paul?} et al.~2010)).

The threshold analysis further reinforces an important methodological
point: the conventional default threshold of 0.5 is not appropriate for
imbalanced ADR datasets. For VKR NMF, the optimal F1 score is achieved
at a threshold of 0.2265, which is substantially lower than the default.
At this operating point, the model achieves a more balanced trade-off
between precision and recall. This indicates that models trained on
imbalanced biomedical data tend to produce conservative probability
estimates for positive cases, and that threshold calibration is
therefore a critical step rather than a post hoc adjustment. Using an
uncalibrated threshold such as 0.5 would result in a substantial loss of
true positive predictions without meaningful gains in specificity
((\textbf{Malone?} et al.~2018)).

From a modelling perspective, the multi-source feature integration
approach used in this study seems to work well. Drug--gene interactions,
chemical fingerprints, and side-effect mappings each capture different
and complementary aspects of drug behaviour. The improvement in AUPR
from the Naïve Baseline to the VKR-based models suggests that these
features contain real biological signal rather than just statistical
patterns. In particular, latent factorisation methods like VKR NMF are
able to effectively use these heterogeneous inputs, showing that the
learned representation space is informative for predicting adverse drug
reactions. An important contribution of the present study is that it
builds upon and extends the framework proposed by (\textbf{Zhong?} et
al.), who demonstrated the effectiveness of combining non-negative
matrix factorisation with kernel regression for adverse drug reaction
prediction using heterogeneous biological information. While their work
established the value of latent factorisation techniques, the current
study broadens this approach by evaluating an extended set of biological
features, including drug--gene interaction profiles, chemical
fingerprints, and side-effect similarity, within a comprehensive
comparative framework. In addition, rather than focusing primarily on
overall discrimination performance, this study places particular
emphasis on the challenges posed by class imbalance by adopting AUPR as
the principal evaluation metric and incorporating threshold optimisation
into the modelling process. The results obtained are broadly consistent
with those of (\textbf{Zhong?} et al.), confirming that latent
factorisation remains an effective strategy for ADR prediction, while
also demonstrating that careful evaluation under imbalanced conditions
provides a more realistic assessment of model performance. Together,
these methodological refinements and the accompanying interactive
implementation represent a practical extension of previous work and
contribute to the development of more interpretable and clinically
relevant computational pharmacovigilance tools.

Despite these positive results, several limitations should be
acknowledged. First, the current framework focuses exclusively on
single-drug adverse reactions and does not account for drug-drug
interactions, which are known to contribute significantly to real-world
adverse events ((\textbf{Dechanont?} et al.~2014)). Second, performance
may degrade for novel drugs with limited structural similarity or sparse
interaction data, since similarity-based approaches rely on sufficient
neighbourhood information for generalisation. Third, the training data
is derived from pharmacovigilance databases that are inherently biased
toward well-studied drugs and frequently reported reactions, introducing
reporting bias that may inflate performance on common drug classes while
limiting generalisability ((\textbf{Hauben?} and Zhou 2012)).

There are several promising directions for future work. Graph neural
networks represent a natural extension of the current framework, as they
can directly model drug-protein and protein-protein interaction networks
in a relational structure rather than relying on flattened feature
representations ((\textbf{Zitnik?} et al.~2018)). Extending the current
framework to drug-drug interaction prediction would also significantly
increase its clinical relevance. In addition, integrating continuously
updated pharmacovigilance databases would help address temporal drift in
drug safety data and improve robustness over time. Finally,
incorporating additional replicate datasets and cross-source validation
would help reduce dataset-specific bias and improve generalisability
across drug classes.

Overall, this study establishes a strong and interpretable baseline
framework for ADR prediction with a rigorous evaluation strategy that
explicitly accounts for class imbalance. By prioritising AUPR as the
main evaluation metric and treating threshold selection as a core
modelling decision, the work provides a more realistic assessment of
predictive performance than approaches that rely primarily on AUROC. The
resulting system is not only analytically robust but also practically
usable through the accompanying interactive application, and it provides
a solid foundation for future extensions in computational drug safety
prediction.

\protect\phantomsection\label{refs}
\begin{CSLReferences}{1}{1}
\bibitem[\citeproctext]{ref-angamo2016}
Angamo, Mirkuzie T., Leanne Chalmers, Colin M. Curtain, and Luke R. E.
Bereznicki. 2016. {``Adverse-Drug-Reaction-Related Hospitalisations in
Developed and Developing Countries: A Review of Prevalence and
Contributing Factors.''} \emph{Drug Safety} 39: 847--57.
\url{https://doi.org/10.1007/s40264-016-0444-7}.

\bibitem[\citeproctext]{ref-formosa2018}
{Formosa, Sigrid et al.} 2018. {``Adverse Drug Reactions in Hospitalized
Patients: Results of the FORWARD Study.''} \emph{Frontiers in
Pharmacology}.

\bibitem[\citeproctext]{ref-freshour2021dgidb}
{Freshour, Sharon L., Susanna Kiwala, Kelsy C. Cotto, et al.} 2021.
{``Integration of the Drug--Gene Interaction Database (DGIdb 4.0) with
Open Crowdsource Efforts.''} \emph{Nucleic Acids Research} 49 (D1):
D1144--51. \url{https://doi.org/10.1093/nar/gkaa1084}.

\bibitem[\citeproctext]{ref-koyama2024}
Koyama, Tomoki, Sae Iinuma, Masaaki Yamamoto, et al. 2024.
{``International Trends in Adverse Drug Event-Related Mortality from
2001 to 2019: An Analysis of the World Health Organization Mortality
Database from 54 Countries.''} \emph{Drug Safety} 47: 237--49.
\url{https://doi.org/10.1007/s40264-023-01387-0}.

\bibitem[\citeproctext]{ref-kuhn2016sider}
Kuhn, Michael, Ivica Letunic, Lars Juhl Jensen, and Peer Bork. 2016.
{``The SIDER Database of Drugs and Side Effects.''} \emph{Nucleic Acids
Research} 44 (D1): D1075--79. \url{https://doi.org/10.1093/nar/gkv1075}.

\bibitem[\citeproctext]{ref-10.1093ux2fbioadvux2fvbae009}
Zhong, Yezhao, Cathal Seoighe, and Haixuan Yang. 2024. {``Non-Negative
Matrix Factorization Combined with Kernel Regression for the Prediction
of Adverse Drug Reaction Profiles.''} \emph{Bioinformatics Advances} 4
(1): vbae009. \url{https://doi.org/10.1093/bioadv/vbae009}.

\end{CSLReferences}

\bibliographystyle{unsrt}
\bibliography{references.bib}


\end{document}
